development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: r7_forum_dev
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: r7_forum_test
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: r7_forum_prod
  username: root
  password: root