development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: r7_forum_dev
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: r7_forum_test
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: r7_forum_production
  username: root
  password: root

#production:
#  adapter: postgresql
#  database: r7_forum_production
#  pool: 5
#  timeout: 5000